version: '2'

services:
  mysql:
    restart: always
    image: mysql:5.6
    container_name: mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql/mysql:/var/lib/mysql
    env_file:
        - variables.env

  php:
    restart: always
    build: ./docker/php-app/
    working_dir: /data
    container_name: php
    command: php-fpm
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - mysql
    volumes:
      - /data/webpages:/data/webpages
    env_file:
      - variables.env

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - /data/webpages:/data/webpages
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites-enable:/etc/nginx/sites-enable
    env_file:
      - variables.env